import type { ThemeConfig } from 'antd'

export const fompTheme: ThemeConfig = {
  token: {
    colorPrimary: '#1e40af',
    colorSuccess: '#27AE60',
    colorWarning: '#E67E22',
    colorError: '#C0392B',
    colorInfo: '#2980B9',
    colorBgBase: '#0D1B2A',
    colorBgContainer: '#1A2E3E',
    colorBgElevated: '#1A2E3E',
    colorBgLayout: '#0D1B2A',
    colorText: '#FFFFFF',
    colorTextSecondary: '#8AB0AD',
    colorTextTertiary: '#5A7A84',
    colorTextDisabled: '#5A7A84',
    colorBorder: '#1E3040',
    colorBorderSecondary: '#1E3040',
    fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
    fontSize: 14,
    fontSizeLG: 16,
    fontSizeXL: 20,
    fontSizeHeading1: 24,
    fontSizeHeading2: 18,
    fontSizeHeading3: 14,
    borderRadius: 6,
    borderRadiusLG: 8,
    controlHeight: 40,
    lineWidth: 1,
  },
  components: {
    Layout: {
      siderBg: '#162230',
      headerBg: '#162230',
      bodyBg: '#0D1B2A',
      triggerBg: '#1E3040',
    },
    Menu: {
      darkItemBg: '#162230',
      darkSubMenuItemBg: '#0D1B2A',
      darkItemSelectedBg: '#1A7A6E',
      darkItemHoverBg: '#1E3040',
      darkItemColor: '#8AB0AD',
      darkItemSelectedColor: '#FFFFFF',
    },
    Table: {
      headerBg: '#162230',
      headerColor: '#8AB0AD',
      rowHoverBg: '#1E3040',
      borderColor: '#1E3040',
      bodySortBg: '#1A2E3E',
    },
    Card: {
      colorBgContainer: '#1A2E3E',
      colorBorderSecondary: '#1E3040',
    },
    Input: {
      colorBgContainer: '#ffffff',
      colorBorder: '#d1d5db',
      activeBorderColor: '#1e40af',
      hoverBorderColor: '#1e40af',
    },
    Select: {
      colorBgContainer: '#ffffff',
      colorBorder: '#d1d5db',
      optionActiveBg: '#f3f4f6',
      optionSelectedBg: '#eff6ff',
    },
    Button: {
      colorPrimary: '#1e40af',
      colorPrimaryHover: '#22A696',
      defaultBg: '#162230',
      defaultBorderColor: '#1E3040',
      defaultColor: '#FFFFFF',
    },
    Modal: {
      contentBg: '#1A2E3E',
      headerBg: '#1A2E3E',
    },
    Drawer: {
      colorBgElevated: '#1A2E3E',
    },
  },
}